#
#   ░████████████████████████████████████████████████████████████████
#   ░██								  ░██
#   ░██                                 ░██    ░█ ░█          ░██ ░██
#   ░██  ░██████████    ░███████████     ░██   ░██          ░███  ░██
#   ░██          ░██    ░██      ░██   ░███████████     ░█████	  ░██
#   ░██         ░██     ░██      ░██     ░██  ░██    ░███  ░██	  ░██
#   ░██       ░███      ░██      ░██     ░██               ░██	  ░██
#   ░██   ░█████        ░███████████     ░████████         ░██	  ░██
#   ░██ 							  ░██
#   ░████████████████████████████████████████████████████████████████
#
#
#    ▄▀█ █░░ ▄▀█ █▀▀ █▀█ █ ▀█▀ ▀█▀ █▄█ ░ ▀█▀ █▀█ █▀▄▀█ █░░
#    █▀█ █▄▄ █▀█ █▄▄ █▀▄ █ ░█░ ░█░ ░█░ ▄ ░█░ █▄█ █░▀░█ █▄▄
#   

[env]
TERM = "xterm-256color"

[font]
size = 12

[window]
dimensions = { columns = 110, lines = 35 }
padding = { x = 10, y = 20 }

[scrolling]
history = 100000
multiplier = 6

# Colors
[colors.normal]
black = "#202020"
white = "#d8d8d8"
cyan = "#FF058A"
magenta = "#E2036F"
blue = "#FF0457"
yellow = "#FF0000"
green = "#FF4D00"
red = "#FF6600"

[colors.bright]
black = "#808080"
white = "#d8d8d8"
cyan = "#FF058A"
magenta = "#E2036F"
blue = "#FF0457"
yellow = "#FF0000"
green = "#FF4D00"
red = "#FF6600"


[colors.dim]
black = "#202020"
white = "#d8d8d8"
cyan = "#FF058A"
magenta = "#E2036F"
blue = "#FF0457"
yellow = "#FF0000"
green = "#FF4D00"
red = "#FF6600"
